### ISSUE TITLE
AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [GAMS-dev/studio#103]
https://github.com/GAMS-dev/studio/blob/8e83f96042e22ffdc96ada7c356500e93e108706/jenkinsfile#L115

Could you please provide the resulting AppImage for download on GitHub Releases? Thank you.

**Comment by MrMontag** [comment]
Yes, I will do that.

**Comment by MrMontag** [comment]
GAMS Studio binary release packages are now available at https://github.com/GAMS-dev/studio/releases
