### ISSUE TITLE
Please add architecture in download file names

### ISSUE THREAD

**Issue by probonopd** [GAMS-dev/studio#124]
Please add the processor architecture in download file names, e.g., please rename `studio-0.8.6.AppImage` to `studio-0.8.6-x86_64.AppImage`. Also may want to use "GAMS" as part of the application name to make it better distinguishable from other similar named applications. Thanks.

Reference: https://github.com/AppImage/appimage.github.io/pull/536

**Comment by MrMontag** [comment]
@probonopd The artifacts have been renamed.
