### ISSUE TITLE
Umlauts in Path -> GDX Open broken

### ISSUE THREAD

**Issue by universal** [GAMS-dev/studio#134]
On trying to open a GDX file, where the parent directory contains an umlaut results in the following error:

```
Unable to open GDX file: /home/XXX/development/repositories/GAMS/XXXIntensitätsstufen_Düngeraufkommen_XXX/tmp/3aggregate.gdx
Error: Ungültiges oder unvollständiges Multi-Byte- oder Wide-Zeichen
```
Symlinking the directory to a path without an umlaut, the gdx file can be opened and viewed just fine.

Environment: Ubuntu 18.04, GAMS - 25.1.1, ntfs formatted drive

On an unrelated side note: This reminded me: Whenever i try to run gams from the command line and the path contains a space, gams does not want to execute the file :(  And I've to symlink the directory, from where it works just fine...

**Comment by MrMontag** [comment]
The umlaut issue has been fixed, which will be part of the upcoming `GAMS Studio 0.9.3`.

For the path with spaces a new ticket has been created (#166).
