### ISSUE TITLE
GDX Viewer: Rearranging the data

### ISSUE THREAD

**Issue by jasdefer** [GAMS-dev/studio#140]
I love the GAMS studio and I already prefer using it over the gams ide.

My top missing feature is to be able to rearrange the data in the GDX viewer:
- Viewing 2-dimensional data in a table
- Viewing indices to a separate filter area

Thanks and keep up the great work.

**Comment by ClemensGAMS** [comment]
Thank you very much for your feedback. What exactly do you mean with the second point? Can you provide an example or a more detailed description?

**Comment by jasdefer** [comment]
In the old gams IDE, it was possible to arrange a variable or parameter so something like this:

![image](https://user-images.githubusercontent.com/5458773/41855944-2e34b4d8-7894-11e8-8f61-d38890e688c7.png)

You can rearrange the indices to:

![image](https://user-images.githubusercontent.com/5458773/41856327-0fd2823a-7895-11e8-8aa3-4291bb08b6b2.png)

It would be awesome to have something similar in the new gams studio.

**Comment by ClemensGAMS** [comment]
GAMS Studio 0.10.3 which is part of the recently published GAMS distribution 26.1.0 provides a basic Table View feature. Currently this feature allows to reshape a GAMS Symbol by moving the last dimension into the column header while all other dimensions remain in the row header. Furthermore, the value columns for variables and equations (level, marginal, lower, upper, scale) can be turned on/off separately. This should cover your specific use case. We plan to make further adjustments to this feature in the future (e.g. moving more than one dimension into the column header and changing the order of dimensions). For more information about how to use this feature please have a look at the documentation: https://www.gams.com/latest/docs/T_STUDIO.html#STUDIO_GDX
