### ISSUE TITLE
Space in path do not work in GAMS on Linux and Mac OS X

### ISSUE THREAD

**Issue by MrMontag** [GAMS-dev/studio#166]
Originally reported in  #134.

> On an unrelated side note: This reminded me: Whenever i try to run gams from the command line and the path contains a space, gams does not want to execute the file :( And I've to symlink the directory, from where it works just fine...

Currently this is a legacy of GAMS on Linux and macOS. If GAMS is used on Windows spaces in paths should work just fine.

**Comment by MrMontag** [comment]
Hi @universal, with the new GAMS 26.0.0 (Beta Release) you can use space in paths on Linux and Mac OS now.

The new GAMS version can be downloaded at https://www.gams.com/beta/

**Comment by universal** [comment]
wonderful! :-) this might seem like a minor thing but simplifies so much. thank you very much :-)
