### ISSUE TITLE
Special german characters not shown correctly in gdx

### ISSUE THREAD

**Issue by arnyeinstein** [GAMS-dev/studio#172]
Hi
German special characters (ü, ä, etc.) are not shown correctly when viewing a gdx file.
Cheers
Renger
File attached is a gdx file.
[gdxfile.txt](https://github.com/GAMS-dev/studio/files/2623360/gdxfile.txt)

**Comment by ClemensGAMS** [comment]
Thank you for reporting this issue. We are working on getting this resolved by allowing to choose an appropriate encoding for GDX files via the "Edit > Encoding" Menu. The fix will be available in the next release.

**Comment by ClemensGAMS** [comment]
The GAMS Studio release 0.10.3 now provides the possibility to change the encoding in the GDX Viewer. It can be accessed through the menu: "Edit" -> "Encoding" -> "Reload With...". This version of GAMS Studio is part of the recently published GAMS distribution 26.1.0.
