### ISSUE TITLE
File modified dialog flooding

### ISSUE THREAD

**Issue by acjbrouwer** [GAMS-dev/studio#173]
On modifying a file loaded in GAMS Studio 0.9.2 outside of GAMS Studio, a **File modified** dialog pops up with the message `<file path> has been modified externally. Reload?`

Not just one but many of these dialogs are opened by GAMS Studio on successive external modifications. To get back to normal, these all have to be confirmed/cancelled.

**Comment by rgoltermann** [comment]
Hello and thank you for your feedback.
This was indeed an issue in version 0.9.2 and fixed in 0.9.4. You could either wait for the next GAMS distribution release or update Studio manually to the newest version (available here: https://github.com/GAMS-dev/studio/releases)

**Comment by acjbrouwer** [comment]
Indeed, I can confirm the issue no longer occurs in 0.9.7
