### ISSUE TITLE
Feature request: GUI scriptability

### ISSUE THREAD

**Issue by acjbrouwer** [GAMS-dev/studio#174]
A means to script GUI elements within the context of GAMS Studio would be helpful. For example through a combination of the embedded code facility and PyQt.

For use cases of such functionality, and an indicator that there is a market for it, have a look at the GAMS Graphical User Interface Generator ([GGIG](http://www.ilr.uni-bonn.de/em/rsrch/ggig/ggig_e.htm)).

**Comment by LutzWestermann** [comment]
Sorry for not replying earlier to your request! This is an interesting feature. Though, we do actually not see this as a perfect fit for our plans we have for Studio. Looking at the "GAMS ecosystem" this goes probably more into the direction of GAMS/MIRO (see https://www.gams.com/miro/ or https://github.com/GAMS-dev/miro),
