### ISSUE TITLE
Error message with o=NUL

### ISSUE THREAD

**Issue by jasdefer** [GAMS-dev/studio#175]
Running a script with `gams transport o=NUL` prevents a `*.lst` file from beeing created. This works as expected, but when doing this in GAMS studio, an error message is displayed:

![error](https://user-images.githubusercontent.com/5458773/51105591-b69be680-17e9-11e9-83c2-a87bc1502902.png)

**Comment by rgoltermann** [comment]
Hello and thank you for your report.
we can confirm that this is a bug and will fix this issue soon.

**Comment by rgoltermann** [comment]
a new GAMS release 26.1.0 is out, which includes GAMS Studio 0.10.3. this version includes a fix for this bug.
