### ISSUE TITLE
Use older distribution for more compatible AppImages

### ISSUE THREAD

**Issue by antoniovazquezblanco** [GAMS-dev/studio#176]
I am trying to run released AppImages under Debian 8 and I am unable to do so due to the fact that AppImages have been built using newer versions of GLBC than the one available in my system.

Is there any possibility to downgrade jenkins OS version for more compatible AppImages?

Thanks in advance

**Comment by MrMontag** [comment]
Hi Antonio,

currently the GAMS Studio AppImage does support Debian 9. Since the Debian Wiki (https://wiki.debian.org/DebianReleases) states that version 8 LTS will end next year June we did not have planed supporting Debian 8, but we consider it. Is a migration to Debian 9 an option for you?

**Comment by antoniovazquezblanco** [comment]
> Is a migration to Debian 9 an option for you?

Not at the moment. The project I am working with is based on Debian 8 machines and that specification cannot be changed.

AFAIK this will also afect many Ubuntu and derived distributions such as Linux Mint among others.

Is downgrading Jenkins an option for you? Meanwhile I will be trying to compile from source but meeting Qt requirements will take me some time.

Thanks!

**Comment by antoniovazquezblanco** [comment]
@MrMontag Any news on this?

Sorry for the ping.

thanks!

**Comment by MrMontag** [comment]
Hi @antoniovazquezblanco, sorry for my late response. This improvement is still on our list but it has a low priority. I going to inform you when we have some progress.

**Comment by antoniovazquezblanco** [comment]
Thank you!
