### ISSUE TITLE
Syntax highlighting gets off-track by a slash

### ISSUE THREAD

**Issue by acjbrouwer** [GAMS-dev/studio#177]
In GAMS Studio 0.9.7, syntax highlighting can get off-track by a slash in a long text of a set definition.

![image](https://user-images.githubusercontent.com/17625243/52327339-1867fe80-29ec-11e9-806c-0be188b400f5.png)

**Comment by rgoltermann** [comment]
Hello,
this bug was fixed in our latest studio release ([download](https://github.com/GAMS-dev/studio/releases/tag/v0.10.5)). Just download the right studio version for your system and replace the existing studio files in your GAMS installation.
