### ISSUE TITLE
Problem with Text in Macintosh Dark Mode

### ISSUE THREAD

**Issue by ackinetics** [GAMS-dev/studio#180]
If you launch Studio on a Macintosh in 10.14 "Dark Mode", most text is white and invisible against the white background of the page. The work around is to switch to "light mode", open Studio, then switch back to "dark mode".

**Comment by LutzWestermann** [comment]
Thanks for the report! Which version of Studio do you use? Actually, this problem should have been fixed with the latest release from last week, see here: https://github.com/GAMS-dev/studio/releases/tag/v0.11.1

**Comment by ackinetics** [comment]
Thank you.  It is fixed.  Sorry, I missed the update.

Regards

**Comment by LutzWestermann** [comment]
No problem, I am glad, that it works for you.
