### ISSUE TITLE
GAMS Studio (X11/CentoOS 7) freezes when a lock file is set

### ISSUE THREAD

**Issue by isuewing** [GAMS-dev/studio#181]
Greetings,

I have successfully installed and run GAMS Studio via the AppImage in a high-performance computing environment running CentOS7.

I wanted to report the the program runs smoothly (great job, folks!), but can exhibit anomalous behavior in the event that a lock file is set. This likely occurred as a result of a network interruption when running GAMS Studio as an X11 application remotely over SSH. It appears that GAMS Studio wants to update the file

~/.config/GAMS/uistates.ini

But if the following file is present

~/.config/GAMS/uistates.ini.lock

then GAMS Studio freezes after about ~30 seconds (or if any command is initiated via a drop-down menu or dialog box) and the X11 window does not refresh. In that instance the only remedy is to terminate the studio process, and zombie window, via kill -9. 

Once the user manually deletes ~/.config/GAMS/uistates.ini.lock , the application runs normally.

I am not sure that this might rise the the level of a bug, but it's certainly something for the FAQ, as it took about a week for my IT support to figure out what was going on.

Regards,

-i

**Comment by rgoltermann** [comment]
Hello and thank you for your informative feedback.
As it happens you found a setup that we havent had incorperated into our testing yet. We will certainly look into it this and try to find a studio based solution for this.
We will post an update here when we found something.

**Comment by rgoltermann** [comment]
Hello again,
last friday we released a new version of Studio which can be downloaded here: https://github.com/GAMS-dev/studio/releases/tag/v0.12.4
We added a potential fix for your problem there. However, we had trouble replicating your issue so we cannot say if this fixes the issue under all circumstances. If your setup and GAMS license allow it we would appreciate if you could try this release and give us feedback if this solves your issue.

kind regards

**Comment by rgoltermann** [comment]
we will close this ticket, as this issue is probably resolved.  
if not feel free to re-open or create a new ticket
