### ISSUE TITLE
Crashes every time when I open a lst file 

### ISSUE THREAD

**Issue by SuXin0526** [GAMS-dev/studio#182]
I am runing a 28.2.0 version of GAMS studio and GAMS on windows10, It just crashes and stops every time when I open the .lst file after a run.

**Comment by LutzWestermann** [comment]
Thanks for the report! Unfortunately, we cannot reproduce this error. Is it with a particular lst file or with any lst file?

One idea for the cause of this: Maybe the settings got messed up when moving from one version of Studio to another. Can you try to start Studio from the command line as 

```
studio.exe --ignore-settings
```

or 

```
studio.exe --reset-settings
```

and check if that makes a difference? The first one will ignore the previous settings just for one session, the latter will reset them to default completely.

**Comment by MrMontag** [comment]
@SuXin0526 Can you check the Event Viewer? Could you post the error messages if there are any issues listed related to Studio?

**Comment by MrMontag** [comment]
The issue is not reproducible. Please reopen if there is new information.
