### ISSUE TITLE
Will not open if CheckForUpdateWrapper::distribIsLatest() hangs

### ISSUE THREAD

**Issue by edscott** [GAMS-dev/studio#183]
Working from behind a proxy, with some apparent network trouble today, application will hang before opening any window. Seems that some timeout is required so that the check for the latest version of gams will not hang gams-studio.

This is the traceback from GDB:

Thread 1 "studio" received signal SIGINT, Interrupt.
0x00007fffee593cfc in recv () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007fffee593cfc in recv () from /usr/lib/libpthread.so.0
#1  0x00007fffd42657c2 in P3UTILS_p3getfromurl(unsigned char const*, unsigned char const*, unsigned short, signed char (*)(void*, int, void*), void*, unsigned char*) () from /opt/gams/gams28.2_linux_x64_64_sfx/libjoatdclib64.so
#2  0x00007fffd426e89b in CHK4UPDATEOBJ_tlicobj_DOT_c4ucheck4update(CHK4UPDATEOBJ_tlicobj_OD_S*) () from /opt/gams/gams28.2_linux_x64_64_sfx/libjoatdclib64.so
#3  0x00007fffd425ed99 in c4ucheck4update () from /opt/gams/gams28.2_linux_x64_64_sfx/libjoatdclib64.so
#4  0x00005555555cba91 in gams::studio::support::CheckForUpdateWrapper::lastDistribVersion (this=0x7fffffffde00) at ../../GAMS/src/support/checkforupdatewrapper.cpp:117
#5  0x00005555555cbbfa in gams::studio::support::CheckForUpdateWrapper::distribIsLatest (this=0x7fffffffde00) at ../../GAMS/src/support/checkforupdatewrapper.cpp:136
#6  0x00005555557c2f92 in gams::studio::HelpWidget::getOnlineStartPageUrl (this=0x555555be8be0) at ../../GAMS/src/help/helpwidget.cpp:568
#7  0x00005555557bed8d in gams::studio::HelpWidget::HelpWidget (this=0x555555be8be0, parent=0x555555aa8330) at ../../GAMS/src/help/helpwidget.cpp:73
#8  0x00005555556675d3 in gams::studio::MainWindow::MainWindow (this=0x555555aa8330, parent=0x0) at ../../GAMS/src/mainwindow.cpp:133
#9  0x00005555555c5cdc in gams::studio::Application::init (this=0x7fffffffe780) at ../../GAMS/src/application.cpp:60
#10 0x0000555555666163 in main (argc=1, argv=0x7fffffffe8e8) at ../../GAMS/src/main.cpp:46

**Comment by MrMontag** [comment]
Thanks for your detailed report. I can confirm that there is an issue if the network connection is interrupted. I inform you as soon as we have a fix.

**Comment by MrMontag** [comment]
Hi @edscott, the startup issue has been fixed and is part of the develop branch. The fix will also be part of Studio 0.12.7, which is planned for this week.
