### ISSUE TITLE
AppImage should include "libjoatdclib64.so"

### ISSUE THREAD

**Issue by Symbian9** [GAMS-dev/studio#184]
Version: `GAMS_Studio-0.12.8-x86_64.AppImage`

On the first launch GAMS Studio could not find `GAMS`, and when I try open "About" dialog it show me warning notification about missed `libjoatdclib64.so`:

```
$ ./GAMS*.AppImage
Error [00:48:44]: Could not find GAMS. Please check your GAMS setup. The installation instructions can be found at www.gams.com/latest/docs/UG_MAIN.html#UG_INSTALL
Current path to GAMS: 
Error [00:49:14]: Could not load shared library libjoatdclib64.so: libjoatdclib64.so: cannot open shared object file: No such file or directory
"[Could not open About GAMS dialog. Could not load shared library libjoatdclib64.so: libjoatdclib64.so: cannot open shared object file: No such file or directory"
```

![pic.1](https://i.imgur.com/L7Qr0Hv.png)

**Comment by MrMontag** [comment]
Hi @Symbian9,
`libjoatdclib64.so` is a library which belongs to the GAMS system. To benefit from the GAMS Studio you need to have GAMS installed. Have you followed the instructions listed at https://www.gams.com/latest/docs/UG_UNIX_INSTALL.html?

**Comment by MrMontag** [comment]
Not an issue. Please install GAMS as described at https://www.gams.com/latest/docs/UG_UNIX_INSTALL.html
