### ISSUE TITLE
Cannot change default solver

### ISSUE THREAD

**Issue by yordiak** [GAMS-dev/studio#185]
In gamside I have specified Gurobi solver as the default one for LP problems. However, when I start GAMS Studio the default solver is CPLEX. 

So, how can I change default solver in GAMS Studio?

System info:
OS: Windows 10
GAMS: 29.1.0
GAMS Studio: 0.13.2

**Comment by rgoltermann** [comment]
hello yordiak,
at the moment it is not possible to use GAMS Studio to set a default solver. this is on our list and will be implemented in the future.  
however, there is a workaround: you can use gamside to set the default solver on system level. Go to Options > Solvers and select "System Default" in the dropdown menu. the solvers you then set as defaults will be used by GAMS, even when using Studio.

i hope that helps for now,
cheers

**Comment by yordiak** [comment]
that's solves the problem. Thanks again
