### ISSUE TITLE
Feauture Request: Automatic semicolon

### ISSUE THREAD

**Issue by yordiak** [GAMS-dev/studio#186]
It could be nice if commands create a block that ends with a semicolon. Such procedure could avoid errors, improving efficiency.

**Comment by LutzWestermann** [comment]
Thanks for this suggestion! It sounds like a good idea, though, it is not really clear, when to trigger the addition of an semicolon. In GAMS, semicolons are often optional in a sense, that putting one or not, does not change the meaning of your code. Also, there are examples where adding one or not is both valid, but the meaning of the code changes, e.g.

```
set i set j /1/;
```

vs.

```
set i; set j /1/;
```

Anyway, we will keep this in mind and probably deal with it in a bigger scope when looking into #157.
