### ISSUE TITLE
Some special characters do not display correctly in Sudio version 0.14.6

### ISSUE THREAD

**Issue by panosev** [GAMS-dev/studio#188]
Hi all, 
there is an issue when special characters are used in the GAMS studio. For instance, I need to read a special character ¤. In Notepad Plus++ (even under different fonts) and GAMSIDE the character is displayed correctly. But, in GAMS Studio not. 

For example, the following statement in GAMSIDE (or Notepad Plus++) is displayed correctly:
SET  v vintage/1900*2100,0,"-","¤"/

But, in GAMS Studio, I get:
SET v vintage/1900*2100,0,"-","�"/

The worst is that this strange character in Studio causes domain violation errors when reading parameters defined over this set via gdxrrw, becuase it does not appear in their data

Best regards
Evangelos Panos

**Comment by rgoltermann** [comment]
hello there,
the IDE and Studio use two different codecs by default. what you could try to do is load your file in studio, and in the menu click on Edit > Encoding > reload with... and select ISO 8859-1 (thats the default IDE codec). Studio will remember the codec you selected for this file. if you want you can convert the file to UTF-8 (that's Studio's default) by using Edit > Encoding > convert to ... UTF-8 but that step is optional.  
let me know if that helped.

Best regards

**Comment by panosev** [comment]
Perfect! The change of Encoding and the reload did the trick. 
Good to know this.
