### ISSUE TITLE
GDX viewer variable tables

### ISSUE THREAD

**Issue by jasdefer** [GAMS-dev/studio#189]
I really love the table view to display symbols in GAMS studio.

When viewing variables in the table view, I always select a single column in the `Value column`: 
![image](https://user-images.githubusercontent.com/5458773/78536246-d30cb000-77ed-11ea-8770-320f6b35eb02.png)

This selection is not stored and after refreshing the *.gdx file, I need to select `Table View` and the `Value column` of my choice again. It would be awesome if the previous selection is stored, or that only a single `Value column` is selected when clicking ong `Table View`.

**Comment by LutzWestermann** [comment]
Thanks for the feedback! This makes a lot of sense. We will keep that in mind for future improvements.

**Comment by LutzWestermann** [comment]
@jasdefer, with the [latest release](https://github.com/GAMS-dev/studio/releases/tag/v1.11.0), we added this feature to Studio.

This Studio release is planned to be published with the upcoming GAMS 40 release.
