### ISSUE TITLE
Crash when loading a particular reference file

### ISSUE THREAD

**Issue by acjbrouwer** [GAMS-dev/studio#190]
GAMS Studio 0.14.4 crashes when loading the attached reference file.

File extension renamed from `.ref` to `.txt` to make GitHub accept the attachment.
[2_activesets.txt](https://github.com/GAMS-dev/studio/files/4485660/2_activesets.txt)

**Comment by rgoltermann** [comment]
hello and thank you for your bug report.
we will address this issue and have a fix ready in the next release of Studio.

best regards
