### ISSUE TITLE
Ubuntu 18.04: Studio 1.0.0 -- Settings export does not work

### ISSUE THREAD

**Issue by universal** [GAMS-dev/studio#192]
I was trying to export the settings to the file through the Settings menu. Hitting export and subsequently save sadly does not create a file. I tried this with the included version from the 31.0 beta release, and the released version from github.

**Comment by rgoltermann** [comment]
hello and thank you for your feedback.  
we can confirm that this is a bug and hope to have a fix ready in the next release of GAMS Studio.

kind regards

**Comment by universal** [comment]
I just did a partial check in the 31.1 release, and at least a settings file is created on hitting export.

**Comment by MrMontag** [comment]
@universal This is fixed with Studio 1.1.1
