### ISSUE TITLE
Feature Request: More themes for syntax highlighting

### ISSUE THREAD

**Issue by yordiak** [GAMS-dev/studio#193]
It would be nice if we would be able to manually edit the color of gams command, comments, etc. 

Ideally, you could provide some options (different themes, like material, dracula, solarizied, etc) on syntax highlighting

**Comment by rgoltermann** [comment]
hello and thanks for your suggestion.
this is indeed something we plan to implement in the future.

we will notify you here when this feature is ready

**Comment by rgoltermann** [comment]
hello yordiak,
we are happy to inform you that the feature you requested made it into Studio! Starting from GAMS Studio version 1.5.2, which can be found here on GitHub or in the latest GAMS34 distribution,  there is a theme editor located under _Settings > Colors_.  
In the editor you can copy existing themes and edit them to your liking. If you want to share your creations there are options to import and export themes.  
in the future we will add additional themes modelled after some of the examples you mentioned.
