### ISSUE TITLE
Run Options not file specific/sticky anymore

### ISSUE THREAD

**Issue by universal** [GAMS-dev/studio#194]
In the studio version from 31.1 it appears that the run options (the text input box above the source window) is not really file/group specific anymore and switches to the last selected value of one file/group for all files. The behavior was different in 30.3.
I hope this is understandable, if not I will try to clarify it with a screenshot or alike :-)

For me this is somewhat unexpected and also counter-productive, as I tend to split code into separate steps that are run in order with restart points and therefore file/group specific run options.

**Comment by LutzWestermann** [comment]
Thank you for reporting this! You are absolutely right, that this is unexpected. It is definitely not intended.

**Comment by MrMontag** [comment]
@universal This has been fixed with Studio 1.1.1
