### ISSUE TITLE
Feature Request: Change the size of tabs

### ISSUE THREAD

**Issue by yordiak** [GAMS-dev/studio#195]
In gams studio you can manually resize -among other- the "project explorer" and the "help" tab. 

It could be really useful if these manually resized tabs to be set as default, so I do not have to resize them each time I open gams studio.

**Comment by LutzWestermann** [comment]
Thank you for the report! Actually, Studio should remember, when you change the size of a widget and restore that size when restarting. So, what you experienced is a bug. We will work on that.

**Comment by LutzWestermann** [comment]
@yordiak , we did some more experiments and seems as if this problem exists "only" when Studio is used maximized or in full screen mode. Can you confirm that? So, if this is also true for you, a workaround would be to work in normal mode, and "maximize" the Studio window by hand. But of course, we will also work on getting the real issue fixed.

**Comment by yordiak** [comment]
@LutzWestermann yes you are right! The problem actually appears in a "maximized" screen mode. The workaround works fine! Thanks for the recommendation!

**Comment by rgoltermann** [comment]
hello,
this bug was fixed in our latest Studio release, which can be found here: https://github.com/GAMS-dev/studio/releases
