### ISSUE TITLE
**** No license specified and no gamslice.txt found in standard locations

### ISSUE THREAD

**Issue by juanfranciscomunoz** [GAMS-dev/studio#196]
**** No license specified and no gamslice.txt found in standard locations.
****
*** Status: Terminated due to a licensing error
***         Request a demo license at www.gams.com/download
***         Inspect listing file for more information
--- Job problema1.gms Stop 07/25/20 22:44:42 elapsed 0:00:00.005

**Comment by LutzWestermann** [comment]
Hi,

Thanks for the report! Could you share some more information about this? How did you get  the message? Where is your license located?

Thanks,
Lutz

**Comment by LutzWestermann** [comment]
We can not do more without additional information. Please reopen the ticket, if you see the need.
