### ISSUE TITLE
Solver lincense information

### ISSUE THREAD

**Issue by jasdefer** [GAMS-dev/studio#197]
Is it possible, that GAMS Studio does not displays the license information correctly? GAMS Studio shows `DEMO` for all solvers, where as the GAMS IDE has different information:

GAMS IDE:
![image](https://user-images.githubusercontent.com/5458773/91290215-a4d73f00-e793-11ea-82e9-b0e8563664d2.png)

GAMS Studio:
![image](https://user-images.githubusercontent.com/5458773/91290263-b1f42e00-e793-11ea-9d1f-420fec3f28fb.png)

Or could I have an error in my GAMS setup? Note, that I can solve problems with CPLEX or other solvers without getting a license error.

**Comment by LutzWestermann** [comment]
Where is your license file located and what version of Studio do you run? We had problems in the past with this dialog, that were fixed with recent release Studio 1.3.3 and 1.3.4 (compare https://github.com/GAMS-dev/studio/releases).

**Comment by jasdefer** [comment]
I should have updated GAMS before posting this, sorry. You are right, updating GAMS Studio fixed the problem. Thank you!
