### ISSUE TITLE
Question: Support other language(s)

### ISSUE THREAD

**Issue by yordiak** [GAMS-dev/studio#198]
I like `gams studio` interface, so I was wondering if you are planning to support other programming languages, like python, julia, R, etc

**Comment by rgoltermann** [comment]
hello and thank you for your inquiry,
in the long run we plan to have basic support for python as part of the GAMS embedded code feature. apart from that we have nothing planned, at least at the moment. this may or may not change over time, however the main focus of Studio will always be the GAMS system.

cheers
