### ISSUE TITLE
Cannot type # in Studio using a Swiss German Keyboard

### ISSUE THREAD

**Issue by panosev** [GAMS-dev/studio#201]
Hi, 
In Swiss-German keyboard the character # is typed by the combination of ALTGR+3 . However, this combination activates in Studio the GAMS options windo. Thus this character cannot by typed with a Swiss-German keyboard in Studio. Whenever I need to type this character, I need to do it in an external editor e.g. notepad, and then copy-paste it in Studio. 
Thanks a lot for your consideration 
Evangelos

**Comment by LutzWestermann** [comment]
Evangelos, thanks for the feedback! `Ctrl + Alt + 3` (which is equivalent to `AltGr + 3`) is defined to open and close the extended command line parameter editor. We will look into redefining this as a shortcut with less conflict potential.

As a (poor) workaround for now you could switch e.g. to an US keyboard layout and use `Shift + 3` to enter the `#` (but you probably know that already).

**Comment by LutzWestermann** [comment]
We changed the problematic shortcut with the latest [Studio release](https://github.com/GAMS-dev/studio/releases/tag/v1.7.0), so that you can hopefully use `#` without any workarounds. That Studio release will be part of the upcoming GAMS 36 release.
