### ISSUE TITLE
Studio crashes when opening GAMS file from macOS finder

### ISSUE THREAD

**Issue by chrispahm** [GAMS-dev/studio#203]
### Description
When double clicking a file in macOS Finder that is associated with GAMS Studio (.gms, .lst, etc.), **and Studio is not open yet**, Studio crashes upon startup. When subsequently clicking the "Open again" button prompted by the macOS error alert, Studio starts up correctly, but does not open the intended file.

https://user-images.githubusercontent.com/20703207/212874682-d30dc5b2-c45a-460b-885a-a603fe5774f0.mp4

When Studio is running in the background, opening the file works just fine!

### Additional information
Tested on 2 Apple Silicon machines running macOS Monterey 12.5.1, GAMS 41.5.0, Studio 1.12.3

[2023-01-17-gams_studio_crash_report.txt](https://github.com/GAMS-dev/studio/files/10434003/2023-01-17-gams_studio_crash_report.txt)

**Comment by MrMontag** [comment]
Thank you for reporting the issue. We are able to reproduce the problem and will provide a fix as soon as possible.

**Comment by Jazzco** [comment]
We fixed the crash. On our systems it looks good now.
