### ISSUE TITLE
Studio from GAMS 42.5.0 has started to exit shortly after launch

### ISSUE THREAD

**Issue by acjbrouwer** [GAMS-dev/studio#210]
Curiously, on the machine of a colleague and also my machine, and a third machine, GAMS studio has stopped working whereas before it definitely was working. The application launches, but then with a brief delay of about 1 second exits again.

This happens on Windows when launched via the start menu, file explorer, or from the command line.

The command line options `--ignore-settings` or `--reset-settings` or `--reset-view` do not resolve the issue. No error messages are visible. The same issue does not occur with the studio that ships with GAMS 41.5 (1.12.3) nor with earlier GAMS installs.

I downloaded the latest release compatible with GAMS 42 from here: https://github.com/GAMS-dev/studio/releases/download/v1.13.5/GAMS_Studio-1.13.5-x86_64.zip  and replaced the `studio` subdirectory of `C:\GAMS\42` with its content, but the odd behavior persists.

Installing GAMS 44.4.0 and launching its studio results in the same behavior: the window briefly shows and then closes.

**Comment by LutzWestermann** [comment]
Thanks for the report! With Studio 1.13 we introduced a feature, that checks for an available update automatically at startup. My first guess from your description would be, that this relates to this change. We learned, that this features can cause trouble in certain environments depending on the system setting. With the latest releases (1.16.x - comes with GAMS 45) we improved the behavior. Could you check, if you still get the error, if you upgrade to that?

**Comment by acjbrouwer** [comment]
With a fresh 45.5 install, studio launches without exiting...

**Comment by acjbrouwer** [comment]
When double clicking on a `.gms` file with the file association pointing to the GAMS 42 studio, studio opens without exiting. Presumably the update check is not performed in that case.

**Comment by LutzWestermann** [comment]
As there seems to be no issue anymore (or at least no way to trigger it with the latest release), I'll close this ticket. Feel free to reopen if you have a different view on this.
