### ISSUE TITLE
GAMS Studio crashes when opening project from the welcome screen 

### ISSUE THREAD

**Issue by panosev** [GAMS-dev/studio#211]
Dear GAMS Studio dev team, 

When trying to open a project, which includes also a GDX file in the project explorer,  GAMS Studio crashes when the project is opened from the recent list of files and projects from the welcome screen. The issue is also valid for GAMS studio 1.17.0 

However the project is opened without problems using the open project menu item, or even by double clicking the project name in windows explorer. 

Best regards
Evangelos

**Comment by LutzWestermann** [comment]
Thanks for the report! Though, so far, I was not able to reproduce the crash. Could you share some more details how to trigger this? I tried this:

- Create a new project from trnsport.gms
- Run with GDX creation
- Close the project
- Double-click at trnport.gsp in the Windows Explorer
  - Works as expected, as you wrote
- Close the project
- Click at trnport.gsp at the Welcome page
  - A project trnsport is created with trnport.gsp as only file included

The behavior I see is definitely wrong, and we need to fix it, but I did not see the crash that you saw.

**Comment by panosev** [comment]
Hi Lutz,

I am attaching an example here.

Open the project normally, ensure that all GMS and GDX files are opened in the tabs of the GAMS Studio as well. Then close the project and try to open it from the welcome screen.

The GAMS Studio in my case is crashing.

I hope you can reproduce the error with the example I send you. Below is a screenshot of trying to open the attached project (debug.gsp) from the welcome screen.

Best regards,
Evangelos

[A screenshot of a computer  Description automatically generated]

__________________________________________
Paul Scherrer Institut
Evangelos Panos
OHSA/E01
Forschungsstrasse 111
5232 Villigen PSI
Schweiz

Telefon: +41563102675
E-Mail: ***@***.***

**Comment by LutzWestermann** [comment]
Unfortunately, there was no attachment. Not sure if the GitHub filtered it? Would it be possible, to send it to support@gams.com instead? 

I tried more things, but was not able to reproduce the crash. Maybe, it depends on the OS? I tried it on Windows. What platform are you working on?

**Comment by panosev** [comment]
Dear Lutz, dear GAMS Studio Dev Team,

I noticed that the crash issue was fixed in the latest release of Studio 1.17.1.

So, you can consider this issue resolved, and you can close it in GitHub.

Thank you very much for taking care of this, which greatly improves the functionality of the Studio together with the other enhancements you made.

Keep up the good work,

Best regards,
Evangelos

__________________________________________
Paul Scherrer Institut
Evangelos Panos
OHSA/E01
Forschungsstrasse 111
5232 Villigen PSI
Schweiz

Telefon: +41563102675
E-Mail: ***@***.***

**Comment by LutzWestermann** [comment]
I am glad to read that it works better for you now! Thanks for the feedback!
